#!/bin/bash

REPOSITORY_NAME=$1
REPOSITORY_ID=$2

[ -f ${DM_HOME}/install/env.properties ] && . ${DM_HOME}/install/env.properties

  cat <<__EOF__
INSTALLER_UI=silent
SERVER.SECURE.ROOT_PASSWORD=root

# Licensing configuration
SERVER.CONFIGURATOR.LICENSING=false
# Licenses
#SERVER.AS_LICENSE=XXXXXXXXXXXX
#SERVER.TCS_LICENSE=XXXXXXXXXXXX
#SERVER.STA_LICENSE=XXXXXXXXXXXX
#SERVER.XHIVE_LICENSE=XXXXXXXXXXXX
#SERVER.CSSL_LICENSE=XXXXXXXXXXXX
#SERVER.RPS_LICENSE=XXXXXXXXXXXX
#SERVER.FRS_LICENSE=XXXXXXXXXXXX
#SERVER.RM_LICENSE=XXXXXXXXXXXX
#SERVER.PRM_LICENSE=XXXXXXXXXXXX

# Docbroker configration
SERVER.CONFIGURATOR.BROKER=false
SERVER.DOCBROKER_ACTION=
SERVER.DOCBROKER_PORT=
SERVER.DOCBROKER_NAME=
SERVER.DOCBROKER_CONNECT_MODE=

# Docbase configuration
SERVER.CONFIGURATOR.REPOSITORY=true
SERVER.DOCBASE_ACTION=CREATE
SERVER.DOCBASE_NAME=$REPOSITORY_NAME
SERVER.DOCBASE_ID=$REPOSITORY_ID
SERVER.DOCBASE_DESCRIPTION=$REPOSITORY_NAME
SERVER.AUTH_DOMAIN=
SERVER.DOCBASE_SIZE=MEDIUM
SERVER.DOCBASE_STARTUP=AUTO

SERVER.DOCUMENTUM_SHARE=$DOCUMENTUM/shared
SERVER.DOCUMENTUM_DATA=$DOCUMENTUM_DATA
SERVER.DOCUMENTUM_DATA_FOR_SAN_NAS=false

SERVER.DOCBASE_SERVICE_NAME=dctm
SERVER.FQDN=localhost
SERVER.CONNECT_MODE=native

SERVER.PROJECTED_DOCBROKER_HOST=broker
SERVER.PROJECTED_DOCBROKER_PORT=$BROKER_PORT_1489_TCP_PORT
SERVER.TEST_DOCBROKER=true

SERVER.USE_EXISTING_DATABASE_ACCOUNT=false
SERVER.DATABASE_CONNECTION=XE
SERVER.DOCBASE_OWNER_NAME=$REPOSITORY_NAME
SERVER.SECURE.DOCBASE_OWNER_PASSWORD=$REPOSITORY_NAME
SERVER.DATABASE_ADMIN_NAME=system
SERVER.SECURE.DATABASE_ADMIN_PASSWORD=oracle

SERVER.NOTIFICATIONS_EMAIL_ACCOUNT=dmadmin@localhost
SERVER.SMTP_SERVER_NAME=localhost

SERVER.GLOBAL_REGISTRY_SPECIFY_OPTION=USE_THIS_REPOSITORY
SERVER.BOF_REGISTRY_USER_LOGIN_NAME=dm_bof_registry
SERVER.SECURE.BOF_REGISTRY_USER_PASSWORD=dm_bof_registry

SERVER.ENABLE_XHIVE=false
SERVER.CONFIGURATOR.DISTRIBUTED_ENV=false
SERVER.ENABLE_RKM=false
START_METHOD_SERVER=false
MORE_DOCBASE=false
SERVER.CONGINUE.MORECOMPONENT=false
__EOF__
